apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gx6u4d2l5-dotnet-basic 
  janus-idp.io/tekton: gx6u4d2l5-dotnet-basic
  backstage.io/kubernetes-id: gx6u4d2l5-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gx6u4d2l5-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  